import math

# Screen settings
# WIDTH, HEIGHT = 800, 600
WIDTH, HEIGHT = 1600, 900
# WIDTH, HEIGHT = 1920, 1080
HALF_WIDTH, HALF_HEIGHT = WIDTH // 2, HEIGHT // 2
FPS = 0

# Player settings
PLAYER_HEALTH = 100
PLAYER_POSITION = 1.5, 5
PLAYER_SIZE = 50
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROTATION_SPEED = 0.002

# Mouse settings
MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_RELATIVE = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - 100

# Ray casting settings
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUMBER_RAYS = WIDTH // 2
HALF_NUMBER_RAYS = NUMBER_RAYS // 2
DELTA_ANGLE = FOV / NUMBER_RAYS
MAX_DEPTH = 20

# 3D settings
SCREEN_DISTANCE = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUMBER_RAYS

# Texture settings
FLOOR_COLOR = 'grey'

# Texture settings
TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2